version: "4"

services:
  k1:
    container_name: k1
    image: kwild:latest
    ports:
      - "8080:8080"
      - "50051:50051"
      - "50151:50151"
      - "26656:26656"
      - "26657:26657"
    environment:
      - LOG=${LOG:-cometbft.log}
      - KWILD_HOME=/app/.kwild
    volumes:
      - ./testnet/node0/:/app/.kwild/
    networks:
      kwilnet:
        ipv4_address: 172.10.100.2
    command: |
      --root-dir=/app/.kwild
      --log.level=debug
      --app.admin-listen-addr=:50151
      --app.grpc-listen-addr=:50051
      --app.http-listen-addr=:8080
      --chain.p2p.external-address=tcp://0.0.0.0:26656
      --chain.rpc.listen-addr=tcp://0.0.0.0:26657

  k2:
    container_name: k2
    image: kwild:latest
    ports:
      - "8081:8080"
      - "50052:50051"
      - "50152:50151"
      - "26666:26656"
      - "26667:26657"
    environment:
      - LOG=${LOG:-cometbft.log}
      - KWILD_HOME=/app/.kwild
    volumes:
      - ./testnet/node1/:/app/.kwild/
    networks:
      kwilnet:
        ipv4_address: 172.10.100.3
    command: |
      --root-dir=/app/.kwild
      --log.level=debug
      --app.admin-listen-addr=:50151
      --app.grpc-listen-addr=:50051
      --app.http-listen-addr=:8080
      --chain.p2p.external-address=tcp://0.0.0.0:26656
      --chain.rpc.laddr=tcp://0.0.0.0:26657

  k3:
    container_name: k3
    image: kwild:latest
    ports:
      - "8082:8080"
      - "50053:50051"
      - "50153:50151"
      - "26676:26656"
      - "26677:26657"
    environment:
      - LOG=${LOG:-cometbft.log}
      - KWILD_HOME=/app/.kwild
    volumes:
      - ./testnet/node2/:/app/.kwild/
    networks:
      kwilnet:
        ipv4_address: 172.10.100.4
    command: |
      --root-dir=/app/.kwild
      --log.level=debug
      --app.admin-listen-addr=:50151
      --app.grpc-listen-addr=:50051
      --app.http-listen-addr=:8080
      --chain.p2p.external-address=tcp://0.0.0.0:26656
      --chain.rpc.laddr=tcp://0.0.0.0:26657


networks:
  kwilnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.100.0/16