// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: balance.sql

package repository

import (
	"context"
)

const getBalanceAndSpent = `-- name: GetBalanceAndSpent :one
SELECT
    balance,
    spent,
    id
FROM
    wallets
WHERE
    wallet = $1
`

type GetBalanceAndSpentRow struct {
	Balance string
	Spent   string
	ID      int32
}

func (q *Queries) GetBalanceAndSpent(ctx context.Context, wallet string) (*GetBalanceAndSpentRow, error) {
	row := q.queryRow(ctx, q.getBalanceAndSpentStmt, getBalanceAndSpent, wallet)
	var i GetBalanceAndSpentRow
	err := row.Scan(&i.Balance, &i.Spent, &i.ID)
	return &i, err
}

const setBalanceAndSpent = `-- name: SetBalanceAndSpent :exec
UPDATE
    wallets
SET
    balance = $2,
    spent = $3
WHERE
    id = $1
`

type SetBalanceAndSpentParams struct {
	ID      int32
	Balance string
	Spent   string
}

func (q *Queries) SetBalanceAndSpent(ctx context.Context, arg *SetBalanceAndSpentParams) error {
	_, err := q.exec(ctx, q.setBalanceAndSpentStmt, setBalanceAndSpent, arg.ID, arg.Balance, arg.Spent)
	return err
}
