// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"database/sql"
)

type Deposit struct {
	DepositID int32
	Txid      string
	Wallet    string
	Amount    sql.NullString
	Height    sql.NullInt64
}

type Height struct {
	Height int64
}

type Wallet struct {
	WalletID int32
	Wallet   string
	Balance  string
	Spent    string
}

type Withdrawal struct {
	WithdrawalID  int32
	CorrelationID string
	WalletID      sql.NullInt32
	Amount        sql.NullString
	Fee           sql.NullString
	Expiry        sql.NullInt64
	Tx            sql.NullString
}
