#!/usr/bin/env bash

# This script ensures that the antlr generated .go files are up-to-date.

pushd $(git rev-parse --show-toplevel)  > /dev/null

# Force regenerate of antlr code
task -f kuneiform:grammar

STATUS=$(git status parse/gen --porcelain)

popd > /dev/null

if [[ -n "$STATUS" ]]; then
    echo "Changes detected in parse/gen !"
    exit 1
else
    echo "No changes detected in the directory."
    exit 0
fi

popd
