#!/usr/bin/env bash

# This script ensures that the generated protobuf .go files are up-to-date.

pushd $(git rev-parse --show-toplevel)  > /dev/null

# Force regenerate of pb Go code.
task -f pb:compile:v1

STATUS=$(git status api/protobuf/tx/v1 --porcelain)

popd > /dev/null

if [[ -n "$STATUS" ]]; then
    echo "Changes detected in api/protobuf/tx/v1 !"
    exit 1
else
    echo "No changes detected in the directory."
    exit 0
fi

popd
