// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: account.sql

package repository

import (
	"context"
)

const getAccount = `-- name: GetAccount :one
SELECT
    balance,
    spent,
    id,
    nonce
FROM
    accounts
WHERE
    account_address = $1
`

type GetAccountRow struct {
	Balance string
	Spent   string
	ID      int32
	Nonce   int64
}

func (q *Queries) GetAccount(ctx context.Context, accountAddress string) (*GetAccountRow, error) {
	row := q.queryRow(ctx, q.getAccountStmt, getAccount, accountAddress)
	var i GetAccountRow
	err := row.Scan(
		&i.Balance,
		&i.Spent,
		&i.ID,
		&i.Nonce,
	)
	return &i, err
}
