# NodePort: map containers port to localhost
service:
  type: NodePort
  # comment nodePorts to enable multi instances on local machine
  nodePorts:
    hasura: 32100


postgresql:
  enabled: true # for dependency
  primary:
    service:
      type: NodePort
      # comment nodePorts to enable multi instances on local machine
      nodePorts:
        postgresql: 32103