code:
  - added|modified: 'go.mod'
  - added|modified: '.github/filters.yaml'
  - added|modified: '.github/workflows/ci.yaml'
  - added|modified: 'contrib/docker/kwild.dockerfile'
  - added|modified: 'contrib/docker/postgres.dockerfile'
  - added|modified: 'contrib/docker/pginit.sql'
  - added|modified: 'contrib/scripts/build/**'
  - added|modified: 'app/**/*.go'
  - added|modified: 'cmd/**/*.go'
  - added|modified: 'common/**/*.go'
  - added|modified: 'config/**/*.go'
  - added|modified: 'extensions/**/*.go'
  - added|modified: 'node/**/*.go'
  - added|modified: 'testing/**'
  - added|modified: 'version/**/*.go'
  - added|modified: 'core/**/*.go'
  - added|modified: 'core/!(*.md)'
  - added|modified: 'core/client/!(*.md)'
  - added|modified: 'core/client/!(example/**)/**'
  - added|modified: 'core/gatewayclient/!(*.md)'
  - added|modified: 'core/gatewayclient/!(example/**)/**'
  - added|modified: 'parse/**'
  - added|modified: 'test/**/*'
  - 'test/!(stress/**)/**'
  - 'parse/!(grammar)/**'
