run:
  timeout: 10m
  go: '1.21'

issues:
  exclude-dirs:
    - core/rpc/protobuf
    - core/rpc/http
    - parse/sql/gen
    - parse/procedures/gen
    - parse/kuneiform/gen
    - parse/actions/gen

output:
  formats:
    - format: github-actions
    - format: colored-line-number

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - durationcheck
    - exportloopref
    - gofmt
    - goimports
    - gosimple
    - govet
    - grouper
    - ineffassign
    - makezero
    - misspell
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - staticcheck
    - sqlclosecheck
    - tparallel
    - typecheck
    - unconvert
    - unused
