project_name: kwil-db

changelog:
  skip: true
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

builds:
  - id: kwil-cli
    binary: kwil-cli
    main: ./cmd/kwil-cli
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/kwilteam/kwil-db/internal/version.KwilVersion={{ index .Env "KWIL_VERSION" }}'
    tags:
      - osusergo
      - netgo
    env:
      - CGO_ENABLED=0

  - id: kwild
    binary: kwild
    main: ./cmd/kwild
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/kwilteam/kwil-db/internal/version.KwilVersion={{ index .Env "KWIL_VERSION" }}'
    tags:
      - osusergo
      - netgo
    env:
      - CGO_ENABLED=0

  - id: kwil-admin
    binary: kwil-admin
    main: ./cmd/kwil-admin
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/kwilteam/kwil-db/internal/version.KwilVersion={{ index .Env "KWIL_VERSION"  }}'
    tags:
      - osusergo
      - netgo
    env:
      - CGO_ENABLED=0

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
  github:
    owner: kwilteam
    name: kwil-cli
  replace_existing_draft: true
  ids:
    - kwil-cli
    - kwild
    - kwil-admin

universal_binaries:
  - replace: true
