project_name: kwil-cli
before:
  hooks:
    - go mod tidy
    - go generate ./...

changelog:
  skip: true
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

builds:
  - id: kwil-cli
    binary: kwil-cli
    main: ./cmd/kwil-cli/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto

universal_binaries:
  - replace: true