project_name: kwil-cli
before:
  hooks:
    - go mod tidy

changelog:
  skip: true
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

builds:
  - id: kwil-cli
    binary: kwil-cli
    main: ./cmd/kwil-cli/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X 'kwil/internal/pkg/build.Version={{.Version}}'
      - -X 'kwil/internal/pkg/build.GitCommit={{.Commit}}'
      - -X 'kwil/internal/pkg/build.BuildTime={{.Date}}'
    env:
      - CGO_ENABLED=0
      - CC_darwin_amd64=o64-clang
      - CCX_darwin_amd64=o64-clang+
      - CC_darwin_arm64=aarch64-apple-darwin20.2-clang
      - CCX_darwin_arm64=aarch64-apple-darwin20.2-clang++
      - CC_windows_amd64=x86_64-w64-mingw32-gc
      - CCX_windows_amd64=x86_64-w64-mingw32-g++
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CCX={{ index .Env (print "CCX_" .Os "_" .Arch) }}'

checksum:
  name_template: 'checksums.txt'

release:
  prerelease: auto
  github:
    owner: kwilteam
    name: kwil-cli
  replace_existing_draft: true
  ids:
    - kwil-cli

universal_binaries:
  - replace: true