version: "3"

includes:
  #note: actual execute directory is the root of the project
  pb: ./api/

tasks:
  default:
    cmds:
      - task -l

  install:deps:
    desc: Install tools required to build this app
    cmds:
      - cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -tI % go install %

  build:
    desc: Build cli & kwild
    cmds:
      - task: build:cli
      - task: build:kwild

  build:cli:
    desc: Build kwil-cli
    cmds:
      - ./scripts/build/binary kwil-cli
    generates:
      - .build/kwil-cli

  build:kwild:
    desc: Builds kwild server
    deps: [pb:compile:v1]
    cmds:
      - ./scripts/build/binary kwild
    generates:
      - .build/kwild

  build:abi:
    desc: Builds Golang bindings for EVM contract ABIs
    internal: true
    cmds:
      - abigen --abi ./pkg/chain/contracts/escrow/evm/abi/escrow.json --bin ./pkg/chain/contracts/escrow/evm/abi/escrow.bin --pkg abi --type Escrow --out ./pkg/chain/contracts/escrow/evm/abi/escrow.go
      - abigen --abi ./pkg/chain/contracts/token/evm/abi/erc20.json --bin ./pkg/chain/contracts/token/evm/abi/erc20.bin --pkg abi --type Erc20 --out ./pkg/chain/contracts/token/evm/abi/erc20.go
    sources:
      - pkg/chain/contracts/*/evm/abi/*.json
      - pkg/chain/contracts/*/evm/abi/*.bin
    generates:
      - pkg/chain/contracts/*/evm/abi/*.go

  # ************ docker ************
  docker:kwild:
    desc: Build the docker image for the kwild
    deps: [ pb:compile:v1 ]
    cmds:
      # pass any args to build debug image, e.g. task docker:kwild -- debug
      - ./scripts/build/docker kwild  {{.CLI_ARGS}}

  # ************ dev ************
  dev:up:
      desc: Start the dev environment
      cmds:
      - go test ./test/acceptance/ -timeout 12h -dev -v
