version: "3"

includes:
  #note: actual execute directory is the root of the project
  pb: ./api/

tasks:
  default:
    cmds:
      - task -l

  install:deps:
    desc: Install tools required to build this app
    cmds:
      - cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -tI % go install %

  vendor:
    desc: Generate vendor
    deps:
      - task: vendor:clean
    cmds:
      - go mod vendor

  vendor:clean:
    desc: Clean vendor
    cmds:
      - rm -rf ./vendor

  git:init:
    desc: Initialize git submodules
    cmds:
      - git submodule update --init

  git:sync:
    desc: Sync git submodules
    cmds:
      - git submodule update --remote

  init:
    desc: Initialize the project
    deps: [install:deps, git:init]
    cmds:
      - go mod download

  build:
    desc: Build cli & kwild
    cmds:
      - task: build:cli
      - task: build:kwild

  build:cli:
    desc: Build kwil-cli
    deps: [pb:compile:v1]
    cmds:
      - ./scripts/build/binary kwil-cli #-mod=mod
    generates:
      - .build/kwil-cli

  build:kwild:
    desc: Builds kwild server
    deps: [pb:compile:v1]
    cmds:
      - ./scripts/build/binary kwild #-mod=mod
    generates:
      - .build/kwild

  build:abi:
    desc: Builds Golang bindings for EVM contract ABIs
    internal: true
    cmds:
      - abigen --abi ./pkg/chain/contracts/escrow/evm/abi/escrow.json --bin ./pkg/chain/contracts/escrow/evm/abi/escrow.bin --pkg abi --type Escrow --out ./pkg/chain/contracts/escrow/evm/abi/escrow.go
      - abigen --abi ./pkg/chain/contracts/token/evm/abi/erc20.json --bin ./pkg/chain/contracts/token/evm/abi/erc20.bin --pkg abi --type Erc20 --out ./pkg/chain/contracts/token/evm/abi/erc20.go
    sources:
      - ./pkg/chain/contracts/*/evm/abi/*.json
      - ./pkg/chain/contracts/*/evm/abi/*.bin
    generates:
      - ./pkg/chain/contracts/*/evm/abi/*.go

  # ************ docker ************
  build:docker:
    desc: Build the docker image for the kwild
    deps: [ pb:compile:v1]
    cmds:
      # need to run after protobuf is compiled
      - task: vendor
      # pass any args to build flavored image, e.g. task build:docker -- debug
      - ./scripts/build/docker kwild {{.CLI_ARGS}} {{.VARIANT}}
      - task: vendor:clean

  publish:dockerhub:
    desc: Publish docker image to dockerhub
    deps: [ pb:compile:v1]
    cmds:
      - task: vendor
      - TAG={{.TAG}} ./scripts/publish/dockerhub
      - task: vendor:clean
    requires:
      vars: [TAG]

  # ************ dev ************
  dev:up:
    desc: Start the dev environment
    deps:
      - task: build:docker
        vars: {VARIANT: 'shell'}
    cmds:
      - go test ./test/acceptance/ -timeout 12h -dev -v
  # ************ test ************
  test:act:
    desc: Run acceptance tests
    deps:
      - task: build:docker
        vars: { VARIANT: 'shell' }
    cmds:
      - go test ./test/acceptance/ -v

  test:act:no-build:
    desc: Run acceptance tests without building docker image
    cmds:
      - go test ./test/acceptance/ -v

  test:unit:
    desc: Run unit tests
    cmds:
      - task vendor
      - go test `go list ./... | grep -v /kwil-db\/test/` -count=1
      - task vendor:clean
