version: "3"

includes:
  #note: actual execute directory is the root of the project
  pb: ./api/

tasks:
  default:
    cmds:
      - task -l

  install:deps:
    aliases: [tools]
    desc: Install tools required to build this app
    cmds:
      - grep _ tools.txt | awk -F'"' '{print $2}' | xargs -tI % go install %

  vendor:
    desc: Generate vendor
    deps:
      - task: vendor:clean
    cmds:
      - go mod vendor

  vendor:clean:
    desc: Clean vendor
    cmds:
      - rm -rf ./vendor

  git:init:
    desc: Initialize git submodules
    cmds:
      - git submodule update --init

  git:sync:
    desc: Sync git submodules
    cmds:
      - git submodule update --remote

  init:
    desc: Initialize the project
    deps: [install:deps, git:init]
    cmds:
      - go mod download

  fmt:
    desc: Format the code
    cmds:
      - goimports -format-only -w .

  lint:
    desc: Lint with golangci-lint
    deps: [pb:compile:v1]
    cmds:
        - golangci-lint run -c .golangci.yml 

  build:
    desc: Build cli & kwild
    cmds:
      - task: build:cli
      - task: build:kwild

  build:cli:
    desc: Build kwil-cli
    deps: [pb:compile:v1]
    cmds:
      - ./scripts/build/binary kwil-cli #-mod=mod
    generates:
      - .build/kwil-cli

  build:kwild:
    desc: Builds kwild server
    deps: [pb:compile:v1]
    cmds:
      - ./scripts/build/binary kwild #-mod=mod
    generates:
      - .build/kwild

  # ************ docker ************
  build:docker:
    desc: Build the docker image for the kwild
    deps: [ pb:compile:v1]
    cmds:
      # need to run after protobuf is compiled
      - task: vendor
      # pass any args to build flavored image, e.g. task build:docker -- debug
      - ./scripts/build/docker kwild {{.CLI_ARGS}} {{.VARIANT}}
      - task: vendor:clean

  publish:dockerhub:
    desc: Publish docker image to dockerhub
    deps: [ pb:compile:v1]
    cmds:
      - task: vendor
      - TAG={{.TAG}} ./scripts/publish/dockerhub
      - task: vendor:clean
    requires:
      vars: [TAG]

  # ************ dev ************
  dev:up:
    desc: Start the dev environment
    deps:
      - task: build:docker
        vars: {VARIANT: 'shell'}
    cmds:
      - task dev:up:nb

  dev:up:nb:
    desc: Start the dev environment without rebuilding docker image
    cmds:
      - go test ./test/acceptance/ -timeout 12h -dev -v

  dev:testnet:up:
    desc: Start the dev environment(with testnet)
    deps:
      - task: build:docker
        vars: { VARIANT: 'shell' }
    cmds:
      - task dev:testnet:up:nb

  dev:testnet:up:nb:
    desc: Start the dev environment(with testnet) without rebuilding docker image
    cmds:
      - go test ./test/integration/ -timeout 12h -dev -v

  # ************ test ************
  test:act:
    desc: Run acceptance tests
    deps:
      - task: build:docker
    cmds:
      - task test:act:nb

  test:act:nb:
    desc: Run acceptance tests without building docker image
    cmds:
      - go test ./test/acceptance/ -count=1 -v

  test:unit:
    desc: Run unit tests
    cmds:
      - go test $(go list ./... | grep -v /kwil-db\/test/) -count=1

  test:unit:race:
      desc: Run unit tests with race
      cmds:
        - task vendor
        - go test `go list ./... | grep -v /kwil-db\/test/` -count=1 -race
        - task vendor:clean
  
  test:it:
    desc: Run integration tests
    deps:
      - task: build:docker
    cmds:
      - task test:it:nb

  test:it:nb:
    desc: Run integration tests
    cmds:
      - go test -count=1 -timeout 0 ./test/integration/ -v
