version: "3"

includes:
  #note: actual execute directory is the root of the project
  docker: ./build/package/docker
  pb: ./api/

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Builds the project
    deps: [build:cli, build:api, build:api-gateway]

  build:cli:
    desc: Builds the kwil-cli
    cmds:
      - go build -o .build/kwil-cli ./cmd/kwil-cli
    generates:
      - .build/kwil-cli

  build:kwild:
    desc: Builds the kwil
    deps: [pb:compile:pricing, pb:compile:config, pb:compile:tx]
    cmds:
      - go build -o .build/kwild ./cmd/kwild
    generates:
      - .build/kwil

  build:sql:
    desc: Generates the SQL repository
    cmds:
      - sqlc generate
    sources:
      - kwil/sql/*.sql
    generates:
      - kwil/repository/gen

  build:gateway:
    desc: Builds the API Gateway
    deps:
      - pb:gen:openapi
    cmds:
      - go build -o .build/kwil-gateway ./cmd/kwil-gateway
    generates:
      - .build/kwil-gateway

  build:abi:
    desc: Builds Golang bindings for EVM contract ABIs
    cmds:
      - abigen --abi ./abi/escrow.json --pkg abi --type Escrow --out ./abi/escrow.go
      - abigen --abi ./abi/erc20.json --pkg abi --type Erc20 --out ./abi/erc20.go

  #  ************ k8s ************
  # have dependencies on docker:kwild and docker:kwil, can't put this section in deployments/helm/Taskfile.yaml
  k8s:helm:update:
    desc: Update the helm charts
    internal: true
    cmds:
      - rm -rf deployments/helm/kwild/charts
      - rm -rf deployments/helm/kwil/charts
      - helm dependency update deployments/helm/hasura
      - helm dependency update deployments/helm/kwild
      - helm dependency update deployments/helm/kwil

  k8s:kwil:
    desc: Build and deploy kwil services to local k8s cluster
    deps:
      - k8s:helm:update
      - docker:kwild
      - docker:kwil-gateway
    cmds:
      - helm install kwil deployments/helm/kwil -f deployments/helm/kwil/dev-values.yaml

  k8s:kwil:install:
    desc: Deploy kwil services to local k8s cluster
    deps:
      - k8s:helm:update
    cmds:
      - helm install kwil deployments/helm/kwil -f deployments/helm/kwil/dev-values.yaml

  k8s:kwil:uninstall:
    desc: Undploy kwil services to local k8s cluster
    cmds:
      - helm uninstall kwil

  k8s:kwild:
    desc: Build and deploy kwil to local k8s cluster
    deps:
      - k8s:helm:update
      - docker:kwild
    cmds:
      - helm install kwild deployments/helm/kwild -f deployments/helm/kwild/dev-values.yaml

  k8s:kwild:install:
    desc: Deploy kwil to local k8s cluster
    deps:
      - k8s:helm:update
    cmds:
      - helm install kwild deployments/helm/kwild -f deployments/helm/kwild/dev-values.yaml

  k8s:kwild:uninstall:
    desc: Undeploy kwild to local k8s cluster
    cmds:
      - helm uninstall kwild
  #  ************ k8s ************

  cli:
    desc: Runs the CLI
    cmds:
      - go run ./cmd/kwil {{.CLI_ARGS}}

  deps:
    desc: Install tools required to build this app
    cmds:
      - cat tools.go | grep _ | awk -F'"' '{print $2}' | xargs -tI % go install %

  go-install:
    cmds:
      - go install {{.REPO}}

  brew-install:
    cmds:
      - brew install {{.PACKAGE}}

  update:submodules:
    desc: Updates git submodules
    cmds:
      - |
        git submodule update --remote