package kslspec

const (
	DiagUnknownDirective          = "Unknown directive"
	DiagMissingDirectiveKey       = "Missing directive key"
	DiagUnknownBlockType          = "Unknown block type"
	DiagUnexpectedDirectiveKey    = "Unexpected directive key"
	DiagUnexpectedDirectiveValue  = "Unexpected directive value"
	DiagMissingDirectiveValue     = "Missing directive value"
	DiagMissingBlockName          = "Missing block name"
	DiagUnexpectedBlockName       = "Unexpected block name"
	DiagUnknownBlockModifier      = "Unknown modifier keyword"
	DiagUnknownBlockLabel         = "Unknown block label"
	DiagUnexpectedAttribute       = "Unexpected attribute"
	DiagUnexpectedBlock           = "Unexpected block"
	DiagUnknownAnnotation         = "Unknown annotation"
	DiagUnexpectedAnnotation      = "Unexpected annotation"
	DiagUnexpectedDeclaration     = "Unexpected declaration"
	DiagDuplicateEnumValue        = "Duplicate enum value"
	DiagUnexpectedEnumValue       = "Unexpected enum value"
	DiagUnexpectedLabelValue      = "Unexpected label value"
	DiagMissingLabelValue         = "Missing label value"
	DiagUnexpectedArg             = "Unexpected argument"
	DiagMissingRequiredArg        = "Missing required argument"
	DiagMissingRequiredKeywordArg = "Missing required keyword argument"
	DiagUnexpectedKeywordArg      = "Unexpected keyword argument"
	DiagDuplicateAttribute        = "Duplicate attribute"
	DiagDuplicateDefinition       = "Duplicate definition"
	DiagUnknownAttribute          = "Unknown attribute"
	DiagMissingRequiredAttribute  = "Missing required attribute"
	DiagUnknownDeclarationType    = "Unknown declaration type"
	DiagDuplicateAnnotation       = "Duplicate annotation"
	DiagDuplicateBlock            = "Duplicate block"
	DiagMissingRequiredAnnotation = "Missing required annotation"
)
