# NodePort: map containers port to localhost
service:
  type: NodePort
  # comment nodePorts to enable multi instances on local machine
  nodePorts:
    kwild: 32101

hasura:
  service:
    type: NodePort
    # comment nodePorts to enable multi instances on local machine
    nodePorts:
      hasura: 32100
  postgresql:
    enabled: true
    primary:
      service:
        type: NodePort
        # comment nodePorts to enable multi instances on local machine
        nodePorts:
          postgresql: 32103

kwildApp:
  fund:
    wallet: 274194b20d248d47c05913c039c65783647e527aa6360e5e143417f8bb50b988
    rpcUrl: wss://goerli.infura.io/ws/v3/745ef5cfaf9d405fb03b10a2c21d1f41
    publicRpcUrl: https://ethereum-goerli-rpc.allthatnode.com
    chainCode: 2
    blockConfirmation: 10
    poolAddress: 0xb0a194286A901FeAEA39D2b765247BEd64aD4F41
  log:
    level: debug