#!/usr/bin/env bash

# This script ensures that the swagger-codegen generated .go files are up-to-date.

pushd $(git rev-parse --show-toplevel)  > /dev/null

# Force regenerate of swagger code
task -f pb:tx:v1:swagger
#task -f pb:function:v0:swagger

STATUS=$(git status core/rpc/http/tx --porcelain)
#STATUS=$(git status core/rpc/http/tx core/rpc/http/function --porcelain)


popd > /dev/null

if [[ -n "$STATUS" ]]; then
    echo "Changes detected in core/rpc/http !"
    exit 1
else
    echo "No changes detected in the directory."
    exit 0
fi

popd
