// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/kwilteam/kwil-db/internal/sqlparse/ast"
	"github.com/kwilteam/kwil-db/internal/sqlparse/catalog"
)

func IntaggFuncs0() []*catalog.Function {
	return []*catalog.Function{
		{
			Name: "int_array_aggregate",
			Args: []*catalog.Argument{
				{
					Type: &ast.TypeName{Name: "integer"},
				},
			},
			ReturnType: &ast.TypeName{Name: "integer[]"},
		},
		{
			Name: "int_array_enum",
			Args: []*catalog.Argument{
				{
					Type: &ast.TypeName{Name: "integer[]"},
				},
			},
			ReturnType: &ast.TypeName{Name: "integer"},
		},
	}
}

func IntaggFuncs() []*catalog.Function {
	funcs := []*catalog.Function{}
	funcs = append(funcs, IntaggFuncs0()...)
	return funcs
}

func Intagg() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = IntaggFuncs()
	return s
}
