// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"github.com/kwilteam/kwil-db/internal/sqlparse/ast"
	"github.com/kwilteam/kwil-db/internal/sqlparse/catalog"
)

func Pgrowlocks() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = []*catalog.Function{
		{
			Name: "pgrowlocks",
			Args: []*catalog.Argument{
				{
					Name: "relname",
					Type: &ast.TypeName{Name: "text"},
				},
			},
			ReturnType: &ast.TypeName{Name: "record"},
		},
	}
	return s
}
