version: "3"

volumes:
  pgkwil:
    driver: local

services:
  pg:
    container_name: postgres-kwild-single
    image: kwildb/postgres:16.4-1
    ports:
      - "15432:5432"
    restart: always
    user: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --data-checksums
      # Setting user/pass/db works, but we use docker-entrypoint-initdb.d instead for more control
      # POSTGRES_USER: kwild
      # POSTGRES_PASSWORD: kwild
      # POSTGRES_DB: kwild
    volumes:
      - pgkwil:/var/lib/postgresql/data
    networks:
      kwilnet0:
        ipv4_address: 172.5.100.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 6s
      retries: 10

  kwild:
    container_name: kwild-single
    image: kwild:latest
    build:
      context: ../../../
      dockerfile: ./build/package/docker/kwild.dockerfile
    ports:
      - "8484:8484"
      - "26656:26656"
      - "26657:26657"
    environment:
      - LOG=${LOG:-cometbft.log}
      - KWILD_HOME=/app/.kwild
    volumes:
      - ./testnode/:/app/.kwild/
    depends_on:
      pg:
        condition: service_healthy
    networks:
      kwilnet0:
        ipv4_address: 172.5.100.2
    command: |
      --autogen
      --root-dir=/app/.kwild
      --log.level=debug
      --app.admin-listen-addr=/tmp/admin.socket
      --chain.p2p.external-address=tcp://0.0.0.0:26656
      --chain.rpc.listen-addr=tcp://0.0.0.0:26657
      --app.pg-db-host=172.5.100.3
      --app.pg-db-port=5432
      --app.pg-db-user=kwild
      --app.pg-db-pass=kwild
    healthcheck:
      test: ["CMD", "curl", "--fail-with-body", "-s", "http://127.0.0.1:8484/api/v1/health/user"]
      interval: 2s
      timeout: 6s
      retries: 10

networks:
  kwilnet0:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.5.100.0/23
