volumes:
  pgkwil:
    driver: local

services:
  pg:
    container_name: postgres-kwild-single
    image: kwildb/postgres:16.5-1
    ports:
      - "15432:5432"
    restart: always
    user: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --data-checksums
      # Setting user/pass/db works, but we use docker-entrypoint-initdb.d instead for more control
      # POSTGRES_USER: kwild
      # POSTGRES_PASSWORD: kwild
      # POSTGRES_DB: kwild
    volumes:
      - pgkwil:/var/lib/postgresql/data
    networks:
      kwilnet0:
        ipv4_address: 172.5.100.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 6s
      retries: 10

  kwild:
    container_name: kwild-single
    image: kwild:latest
    build:
      context: ../../../../../
      dockerfile: ../../kwild.dockerfile
    ports:
      - "8484:8484"
      - "6600:6600"
    environment:
      - KWILD_ROOT=/app/.kwild
    volumes:
      - ./testnode/:/app/.kwild/
    depends_on:
      pg:
        condition: service_healthy
    networks:
      kwilnet0:
        ipv4_address: 172.5.100.2
    command: |
      --autogen
      --root=/app/.kwild
      --log-format=plain
      --log-level=debug
      --admin.listen=/tmp/kwild.socket
      --rpc.listen=0.0.0.0:8484
      --p2p.listen=0.0.0.0:6600
      --consensus.propose-timeout=200ms
      --consensus.empty-block-timeout=6s
      --db.host=172.5.100.3
      --db.port=5432
      --db.user=kwild
      --db.pass=kwild
    healthcheck:
      test: ["CMD", "curl", "--fail-with-body", "-s", "http://127.0.0.1:8484/api/v1/health/user"]
      interval: 2s
      timeout: 6s
      retries: 10

networks:
  kwilnet0:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.5.100.0/23
