#!/usr/bin/env sh
#
# Build and push the Kwil postgres docker image
#

set -eu

ROOT=$(dirname "$0")/../..

cd "$ROOT"/build/package/docker

: ${TAG:=latest}

echo Building kwild for multiarch and pushing to dockerhub, tag: ${TAG}

docker build --platform linux/amd64,linux/arm64/v8 -t kwildb/postgres:${TAG} \
    --label "postgres configured for Kwil DB" \
    --push -f postgres.dockerfile .
