/*
 * kwil/tx/v1/account.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TxTxQueryResponse struct {
	Hash string `json:"hash,omitempty"`
	Height string `json:"height,omitempty"`
	Tx *TxTransaction `json:"tx,omitempty"`
	TxResult *TxTransactionResult `json:"tx_result,omitempty"`
}
