/*
 * kwil/tx/v1/account.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TxValidatorJoinStatusResponse struct {
	ApprovedValidators []string `json:"approved_validators,omitempty"`
	PendingValidators []string `json:"pending_validators,omitempty"`
	Power string `json:"power,omitempty"`
}
