/*
 * kwil/tx/v1/account.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TxProcedure struct {
	Name string `json:"name,omitempty"`
	Parameters []TxTypedVariable `json:"parameters,omitempty"`
	Public bool `json:"public,omitempty"`
	Modifiers []string `json:"modifiers,omitempty"`
	Body string `json:"body,omitempty"`
	ReturnTypes *TxProcedureReturn `json:"return_types,omitempty"`
	Annotations []string `json:"annotations,omitempty"`
}
