name: Discussion
description: Discuss topics related to kwil-db that may lead to a feature request or bug report.
title: "Discussion: "
labels: ["discussion"]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for taking the time to discuss a topic related to kwil-db. This should be for discussing topics related to **tangible changes to the kwil-db codebase**.
              
              Feel free to discuss general features or topics in the [Discord server](https://discord.com/invite/HzRPZ59Kay).
    - type: input
      id: subject
      attributes:
          label: Discussion Subject
          description: One sentence description of the discussion.
          placeholder: e.g. I would like to discuss the following topic...
      validations:
          required: true
    - type: textarea
      id: details
      attributes:
          label: Discussion Details
          description: Go further into detail about the discussion topic.
          placeholder: e.g. I have been thinking a lot about how we handle signature verification...
      validations:
          required: true