openapi: 3.0.1
info:
  title: kwil/function/v0/messages.proto
  version: version not set
servers:
- url: /
tags:
- name: FunctionService
paths:
  /api/v1/verify_signature:
    post:
      tags:
      - FunctionService
      operationId: FunctionService_VerifySignature
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/functionVerifySignatureRequest'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/functionVerifySignatureResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
components:
  schemas:
    functionVerifySignatureRequest:
      type: object
      properties:
        signature:
          $ref: '#/components/schemas/txSignature'
        sender:
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
          format: byte
        msg:
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
          format: byte
    functionVerifySignatureResponse:
      type: object
      properties:
        valid:
          type: boolean
        error:
          type: string
      example:
        valid: true
        error: error
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        type: object
      x-schema-name: protobufAny
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
    txSignature:
      type: object
      properties:
        signature_bytes:
          pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
          type: string
          format: byte
        signature_type:
          type: string
x-original-swagger-version: "2.0"
