services:
  pg:
    container_name: postgres
    image: kwildb/postgres:16.4-1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --data-checksums
      # Setting user/pass/db works, but we use docker-entrypoint-initdb.d instead for more control
      # POSTGRES_USER: kwild
      # POSTGRES_PASSWORD: kwild
      # POSTGRES_DB: kwild
    volumes: 
      - kwildb:/var/lib/postgresql/data

volumes:
  kwildb:
    driver: local
