// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"kwil/x/sql/catalog"
)

func IntarrayFuncs0() []*catalog.Function {
	return []*catalog.Function{
		{
			Name: "_int_contained",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_int_contains",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_int_different",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_int_inter",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "_int_overlap",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_int_same",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_int_union",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "_intbig_in",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "cstring"},
				},
			},
			ReturnType: &catalog.QualName{Name: "intbig_gkey"},
		},
		{
			Name: "_intbig_out",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "intbig_gkey"},
				},
			},
			ReturnType: &catalog.QualName{Name: "cstring"},
		},
		{
			Name: "boolop",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "query_int"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "bqarr_in",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "cstring"},
				},
			},
			ReturnType: &catalog.QualName{Name: "query_int"},
		},
		{
			Name: "bqarr_out",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "query_int"},
				},
			},
			ReturnType: &catalog.QualName{Name: "cstring"},
		},
		{
			Name: "icount",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer"},
		},
		{
			Name: "idx",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer"},
		},
		{
			Name: "intarray_del_elem",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "intarray_push_array",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "intarray_push_elem",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "intset",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "intset_subtract",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "intset_union_elem",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "querytree",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "query_int"},
				},
			},
			ReturnType: &catalog.QualName{Name: "text"},
		},
		{
			Name: "rboolop",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "query_int"},
				},
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "sort",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "sort",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "sort_asc",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "sort_desc",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "subarray",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "subarray",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
		{
			Name: "uniq",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "integer[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer[]"},
		},
	}
}

func IntarrayFuncs() []*catalog.Function {
	funcs := []*catalog.Function{}
	funcs = append(funcs, IntarrayFuncs0()...)
	return funcs
}

func Intarray() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = IntarrayFuncs()
	return s
}
