// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"kwil/x/sql/catalog"
)

func LtreeFuncs0() []*catalog.Function {
	return []*catalog.Function{
		{
			Name: "_lt_q_regex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "lquery[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_lt_q_rregex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "lquery[]"},
				},
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_ltq_extract_regex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "lquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "_ltq_regex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "lquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_ltq_rregex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "lquery"},
				},
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_ltree_extract_isparent",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "_ltree_extract_risparent",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "_ltree_isparent",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_ltree_r_isparent",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_ltree_r_risparent",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_ltree_risparent",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_ltxtq_exec",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "ltxtquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "_ltxtq_extract_exec",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
				{
					Type: &catalog.QualName{Name: "ltxtquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "_ltxtq_rexec",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltxtquery"},
				},
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "index",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer"},
		},
		{
			Name: "index",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer"},
		},
		{
			Name: "lca",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "lca",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "lca",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "lca",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "lca",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "lca",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "lca",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "lca",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "lquery_in",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "cstring"},
				},
			},
			ReturnType: &catalog.QualName{Name: "lquery"},
		},
		{
			Name: "lquery_out",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "lquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "cstring"},
		},
		{
			Name: "lquery_send",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "lquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "bytea"},
		},
		{
			Name: "lt_q_regex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "lquery[]"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "lt_q_rregex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "lquery[]"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltq_regex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "lquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltq_rregex",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "lquery"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree2text",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "text"},
		},
		{
			Name: "ltree_addltree",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "ltree_addtext",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "ltree_cmp",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer"},
		},
		{
			Name: "ltree_eq",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree_ge",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree_gist_in",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "cstring"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree_gist"},
		},
		{
			Name: "ltree_gist_out",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree_gist"},
				},
			},
			ReturnType: &catalog.QualName{Name: "cstring"},
		},
		{
			Name: "ltree_gt",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree_in",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "cstring"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "ltree_isparent",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree_le",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree_lt",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree_ne",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree_out",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "cstring"},
		},
		{
			Name: "ltree_risparent",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltree_send",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "bytea"},
		},
		{
			Name: "ltree_textadd",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "ltxtq_exec",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "ltxtquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltxtq_in",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "cstring"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltxtquery"},
		},
		{
			Name: "ltxtq_out",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltxtquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "cstring"},
		},
		{
			Name: "ltxtq_rexec",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltxtquery"},
				},
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "ltxtq_send",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltxtquery"},
				},
			},
			ReturnType: &catalog.QualName{Name: "bytea"},
		},
		{
			Name: "nlevel",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
			},
			ReturnType: &catalog.QualName{Name: "integer"},
		},
		{
			Name: "subltree",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "subpath",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "subpath",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "ltree"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
				{
					Type: &catalog.QualName{Name: "integer"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
		{
			Name: "text2ltree",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "ltree"},
		},
	}
}

func LtreeFuncs() []*catalog.Function {
	funcs := []*catalog.Function{}
	funcs = append(funcs, LtreeFuncs0()...)
	return funcs
}

func Ltree() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = LtreeFuncs()
	return s
}
