// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"kwil/x/sql/catalog"
)

func PgTrgmFuncs0() []*catalog.Function {
	return []*catalog.Function{
		{
			Name: "gtrgm_in",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "cstring"},
				},
			},
			ReturnType: &catalog.QualName{Name: "gtrgm"},
		},
		{
			Name: "gtrgm_out",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "gtrgm"},
				},
			},
			ReturnType: &catalog.QualName{Name: "cstring"},
		},
		{
			Name: "set_limit",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "real"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name:       "show_limit",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "show_trgm",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "text[]"},
		},
		{
			Name: "similarity",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "similarity_dist",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "similarity_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "strict_word_similarity",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "strict_word_similarity_commutator_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "strict_word_similarity_dist_commutator_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "strict_word_similarity_dist_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "strict_word_similarity_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "word_similarity",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "word_similarity_commutator_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name: "word_similarity_dist_commutator_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "word_similarity_dist_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "real"},
		},
		{
			Name: "word_similarity_op",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
	}
}

func PgTrgmFuncs() []*catalog.Function {
	funcs := []*catalog.Function{}
	funcs = append(funcs, PgTrgmFuncs0()...)
	return funcs
}

func PgTrgm() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = PgTrgmFuncs()
	return s
}
