// Code generated by sqlc-pg-gen. DO NOT EDIT.

package contrib

import (
	"kwil/x/sql/catalog"
)

func SslinfoFuncs0() []*catalog.Function {
	return []*catalog.Function{
		{
			Name:       "ssl_cipher",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "text"},
		},
		{
			Name:       "ssl_client_cert_present",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name:       "ssl_client_dn",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "text"},
		},
		{
			Name: "ssl_client_dn_field",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "text"},
		},
		{
			Name:       "ssl_client_serial",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "numeric"},
		},
		{
			Name:       "ssl_extension_info",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "record"},
		},
		{
			Name:       "ssl_is_used",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "boolean"},
		},
		{
			Name:       "ssl_issuer_dn",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "text"},
		},
		{
			Name: "ssl_issuer_field",
			Args: []*catalog.Argument{
				{
					Type: &catalog.QualName{Name: "text"},
				},
			},
			ReturnType: &catalog.QualName{Name: "text"},
		},
		{
			Name:       "ssl_version",
			Args:       []*catalog.Argument{},
			ReturnType: &catalog.QualName{Name: "text"},
		},
	}
}

func SslinfoFuncs() []*catalog.Function {
	funcs := []*catalog.Function{}
	funcs = append(funcs, SslinfoFuncs0()...)
	return funcs
}

func Sslinfo() *catalog.Schema {
	s := &catalog.Schema{Name: "pg_catalog"}
	s.Funcs = SslinfoFuncs()
	return s
}
