// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: kwil/apisvc/schema.proto

package apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploySchemaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx *Tx `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *DeploySchemaRequest) Reset() {
	*x = DeploySchemaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kwil_apisvc_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploySchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploySchemaRequest) ProtoMessage() {}

func (x *DeploySchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kwil_apisvc_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploySchemaRequest.ProtoReflect.Descriptor instead.
func (*DeploySchemaRequest) Descriptor() ([]byte, []int) {
	return file_kwil_apisvc_schema_proto_rawDescGZIP(), []int{0}
}

func (x *DeploySchemaRequest) GetTx() *Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

type DeploySchemaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeploySchemaResponse) Reset() {
	*x = DeploySchemaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kwil_apisvc_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeploySchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploySchemaResponse) ProtoMessage() {}

func (x *DeploySchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kwil_apisvc_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploySchemaResponse.ProtoReflect.Descriptor instead.
func (*DeploySchemaResponse) Descriptor() ([]byte, []int) {
	return file_kwil_apisvc_schema_proto_rawDescGZIP(), []int{1}
}

func (x *DeploySchemaResponse) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *DeploySchemaResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DropDatabaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx *Tx `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *DropDatabaseRequest) Reset() {
	*x = DropDatabaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kwil_apisvc_schema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatabaseRequest) ProtoMessage() {}

func (x *DropDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kwil_apisvc_schema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatabaseRequest.ProtoReflect.Descriptor instead.
func (*DropDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_kwil_apisvc_schema_proto_rawDescGZIP(), []int{2}
}

func (x *DropDatabaseRequest) GetTx() *Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

type DropDatabaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Txid string `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DropDatabaseResponse) Reset() {
	*x = DropDatabaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kwil_apisvc_schema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatabaseResponse) ProtoMessage() {}

func (x *DropDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kwil_apisvc_schema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatabaseResponse.ProtoReflect.Descriptor instead.
func (*DropDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_kwil_apisvc_schema_proto_rawDescGZIP(), []int{3}
}

func (x *DropDatabaseResponse) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *DropDatabaseResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_kwil_apisvc_schema_proto protoreflect.FileDescriptor

var file_kwil_apisvc_schema_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6b, 0x77, 0x69, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x76, 0x63, 0x2f, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x73,
	0x76, 0x63, 0x1a, 0x14, 0x6b, 0x77, 0x69, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x76, 0x63, 0x2f,
	0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x13, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x70,
	0x69, 0x73, 0x76, 0x63, 0x2e, 0x54, 0x78, 0x52, 0x02, 0x74, 0x78, 0x22, 0x3c, 0x0a, 0x14, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x31, 0x0a, 0x13, 0x44, 0x72, 0x6f,
	0x70, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61,
	0x70, 0x69, 0x73, 0x76, 0x63, 0x2e, 0x54, 0x78, 0x52, 0x02, 0x74, 0x78, 0x22, 0x3c, 0x0a, 0x14,
	0x44, 0x72, 0x6f, 0x70, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x78, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x14, 0x5a, 0x12, 0x6b, 0x77,
	0x69, 0x6c, 0x2f, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kwil_apisvc_schema_proto_rawDescOnce sync.Once
	file_kwil_apisvc_schema_proto_rawDescData = file_kwil_apisvc_schema_proto_rawDesc
)

func file_kwil_apisvc_schema_proto_rawDescGZIP() []byte {
	file_kwil_apisvc_schema_proto_rawDescOnce.Do(func() {
		file_kwil_apisvc_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_kwil_apisvc_schema_proto_rawDescData)
	})
	return file_kwil_apisvc_schema_proto_rawDescData
}

var file_kwil_apisvc_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kwil_apisvc_schema_proto_goTypes = []interface{}{
	(*DeploySchemaRequest)(nil),  // 0: apisvc.DeploySchemaRequest
	(*DeploySchemaResponse)(nil), // 1: apisvc.DeploySchemaResponse
	(*DropDatabaseRequest)(nil),  // 2: apisvc.DropDatabaseRequest
	(*DropDatabaseResponse)(nil), // 3: apisvc.DropDatabaseResponse
	(*Tx)(nil),                   // 4: apisvc.Tx
}
var file_kwil_apisvc_schema_proto_depIdxs = []int32{
	4, // 0: apisvc.DeploySchemaRequest.tx:type_name -> apisvc.Tx
	4, // 1: apisvc.DropDatabaseRequest.tx:type_name -> apisvc.Tx
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kwil_apisvc_schema_proto_init() }
func file_kwil_apisvc_schema_proto_init() {
	if File_kwil_apisvc_schema_proto != nil {
		return
	}
	file_kwil_apisvc_tx_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kwil_apisvc_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploySchemaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kwil_apisvc_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeploySchemaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kwil_apisvc_schema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropDatabaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kwil_apisvc_schema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropDatabaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kwil_apisvc_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kwil_apisvc_schema_proto_goTypes,
		DependencyIndexes: file_kwil_apisvc_schema_proto_depIdxs,
		MessageInfos:      file_kwil_apisvc_schema_proto_msgTypes,
	}.Build()
	File_kwil_apisvc_schema_proto = out.File
	file_kwil_apisvc_schema_proto_rawDesc = nil
	file_kwil_apisvc_schema_proto_goTypes = nil
	file_kwil_apisvc_schema_proto_depIdxs = nil
}
