package validation

import "strings"

func IsKeyword(str string) bool {
	upperWord := strings.ToLower(str)

	_, ok := reservedWords[upperWord]
	return ok
}

// resevred words are based on Postgres's reserved words:
// https://www.postgresql.org/docs/16/sql-keywords-appendix.html
var reservedWords = map[string]struct{}{
	"all":               {},
	"analyse":           {},
	"analyze":           {},
	"and":               {},
	"any":               {},
	"array":             {},
	"as":                {},
	"asc":               {},
	"asymmetric":        {},
	"authorization":     {},
	"binary":            {},
	"both":              {},
	"case":              {},
	"cast":              {},
	"check":             {},
	"collate":           {},
	"collation":         {},
	"column":            {},
	"concurrently":      {},
	"constraint":        {},
	"create":            {},
	"cross":             {},
	"current_catalog":   {},
	"current_date":      {},
	"current_role":      {},
	"current_schema":    {},
	"current_time":      {},
	"current_timestamp": {},
	"current_user":      {},
	"default":           {},
	"deferrable":        {},
	"desc":              {},
	"distinct":          {},
	"do":                {},
	"else":              {},
	"end":               {},
	"except":            {},
	"false":             {},
	"fetch":             {},
	"for":               {},
	"foreign":           {},
	"freeze":            {},
	"from":              {},
	"full":              {},
	"grant":             {},
	"group":             {},
	"having":            {},
	"ilike":             {},
	"in":                {},
	"initially":         {},
	"inner":             {},
	"intersect":         {},
	"into":              {},
	"is":                {},
	"isnull":            {},
	"join":              {},
	"lateral":           {},
	"leading":           {},
	"left":              {},
	"like":              {},
	"limit":             {},
	"localtime":         {},
	"localtimestamp":    {},
	"natural":           {},
	"not":               {},
	"notnull":           {},
	"null":              {},
	"offset":            {},
	"on":                {},
	"only":              {},
	"or":                {},
	"order":             {},
	"outer":             {},
	"overlaps":          {},
	"placing":           {},
	"primary":           {},
	"references":        {},
	"returning":         {},
	"right":             {},
	"select":            {},
	"session_user":      {},
	"similar":           {},
	"some":              {},
	"symmetric":         {},
	"system_user":       {},
	"table":             {},
	"tablesample":       {},
	"then":              {},
	"to":                {},
	"trailing":          {},
	"true":              {},
	"union":             {},
	"unique":            {},
	"user":              {},
	"using":             {},
	"variadic":          {},
	"verbose":           {},
	"when":              {},
	"where":             {},
	"window":            {},
	"with":              {},
	// below are keywords that are not restricted by postgres, but are
	// restricted by kwil
	"excluded": {},
}
