package pgschema

import (
	"errors"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"unicode"

	"kwil/x/schemadef/sqlschema"
	"kwil/x/sql/sqlutil"
)

// A diff provides a PostgreSQL implementation for sqlschema.DiffDriver.
type diff struct{}

func NewDiffer() sqlschema.Differ {
	return &sqlschema.Diff{DiffDriver: &diff{}}
}

// SchemaAttrDiff returns a changeset for migrating schema attributes from one state to the other.
func (d *diff) SchemaAttrDiff(_, _ *sqlschema.Schema) []sqlschema.SchemaChange {
	// No special schema attribute diffing for PostgreSQL.
	return nil
}

// TableAttrDiff returns a changeset for migrating table attributes from one state to the other.
func (d *diff) TableAttrDiff(from, to *sqlschema.Table) ([]sqlschema.SchemaChange, error) {
	var changes []sqlschema.SchemaChange
	if change := sqlschema.CommentDiff(from.Attrs, to.Attrs); change != nil {
		changes = append(changes, change)
	}
	if err := d.partitionChanged(from, to); err != nil {
		return nil, err
	}
	return append(changes, sqlschema.CheckDiff(from, to, func(c1, c2 *sqlschema.Check) bool {
		return sqlschema.Has(c1.Attrs, &NoInherit{}) == sqlschema.Has(c2.Attrs, &NoInherit{})
	})...), nil
}

// ColumnChange returns the schema changes (if any) for migrating one column to the other.
func (d *diff) ColumnChange(_ *sqlschema.Table, from, to *sqlschema.Column) (sqlschema.ChangeKind, error) {
	change := sqlschema.CommentChange(from.Attrs, to.Attrs)
	if from.Type.Nullable != to.Type.Nullable {
		change |= sqlschema.ChangeNullability
	}
	changed, err := d.typeChanged(from, to)
	if err != nil {
		return sqlschema.NoChange, err
	}
	if changed {
		change |= sqlschema.ChangeType
	}
	if changed, err = d.defaultChanged(from, to); err != nil {
		return sqlschema.NoChange, err
	}
	if changed {
		change |= sqlschema.ChangeDefault
	}
	if identityChanged(from.Attrs, to.Attrs) {
		change |= sqlschema.ChangeAttr
	}
	if changed, err = d.generatedChanged(from, to); err != nil {
		return sqlschema.NoChange, err
	}
	if changed {
		change |= sqlschema.ChangeGenerated
	}
	return change, nil
}

// defaultChanged reports if the default value of a column was changed.
func (d *diff) defaultChanged(from, to *sqlschema.Column) (bool, error) {
	d1, ok1 := sqlschema.DefaultValue(from)
	d2, ok2 := sqlschema.DefaultValue(to)
	if ok1 != ok2 {
		return true, nil
	}
	if trimCast(d1) == trimCast(d2) {
		return false, nil
	}
	return true, nil
}

// generatedChanged reports if the generated expression of a column was changed.
func (*diff) generatedChanged(from, to *sqlschema.Column) (bool, error) {
	var fromX, toX sqlschema.GeneratedExpr
	switch fromHas, toHas := sqlschema.Has(from.Attrs, &fromX), sqlschema.Has(to.Attrs, &toX); {
	case fromHas && toHas && sqlutil.MayWrap(fromX.Expr) != sqlutil.MayWrap(toX.Expr):
		return false, fmt.Errorf("changing the generation expression for a column %q is not supported", from.Name)
	case !fromHas && toHas:
		return false, fmt.Errorf("changing column %q to generated column is not supported (drop and add is required)", from.Name)
	default:
		// Only DROP EXPRESSION is supported.
		return fromHas && !toHas, nil
	}
}

// partitionChanged checks and returns an error if the partition key of a table was changed.
func (*diff) partitionChanged(from, to *sqlschema.Table) error {
	var fromP, toP Partition
	switch fromHas, toHas := sqlschema.Has(from.Attrs, &fromP), sqlschema.Has(to.Attrs, &toP); {
	case fromHas && !toHas:
		return fmt.Errorf("partition key cannot be dropped from %q (drop and add is required)", from.Name)
	case !fromHas && toHas:
		return fmt.Errorf("partition key cannot be added to %q (drop and add is required)", to.Name)
	case fromHas && toHas:
		s1, err := formatPartition(fromP)
		if err != nil {
			return err
		}
		s2, err := formatPartition(toP)
		if err != nil {
			return err
		}
		if s1 != s2 {
			return fmt.Errorf("partition key of table %q cannot be changed from %s to %s (drop and add is required)", to.Name, s1, s2)
		}
	}
	return nil
}

// IsGeneratedIndexName reports if the index name was generated by the database.
func (d *diff) IsGeneratedIndexName(t *sqlschema.Table, idx *sqlschema.Index) bool {
	names := make([]string, len(idx.Parts))
	for i, p := range idx.Parts {
		if p.Column == nil {
			return false
		}
		names[i] = p.Column.Name
	}
	// Auto-generate index names will have the following format: <table>_<c1>_..._key.
	// In case of conflict, PostgreSQL adds additional index at the end (e.g. "key1").
	p := fmt.Sprintf("%s_%s_key", t.Name, strings.Join(names, "_"))
	if idx.Name == p {
		return true
	}
	i, err := strconv.ParseInt(strings.TrimPrefix(idx.Name, p), 10, 64)
	return err == nil && i > 0
}

// IndexAttrChanged reports if the index attributes were changed.
// The default type is BTREE if no type was specified.
func (*diff) IndexAttrChanged(from, to []sqlschema.Attr) bool {
	t1 := &IndexType{T: IndexTypeBTree}
	if sqlschema.Has(from, t1) {
		t1.T = strings.ToUpper(t1.T)
	}
	t2 := &IndexType{T: IndexTypeBTree}
	if sqlschema.Has(to, t2) {
		t2.T = strings.ToUpper(t2.T)
	}
	if t1.T != t2.T {
		return true
	}
	var p1, p2 IndexPredicate
	if sqlschema.Has(from, &p1) != sqlschema.Has(to, &p2) || (p1.Predicate != p2.Predicate && p1.Predicate != sqlutil.MayWrap(p2.Predicate)) {
		return true
	}
	if indexIncludeChanged(from, to) {
		return true
	}
	s1, ok1 := indexStorageParams(from)
	s2, ok2 := indexStorageParams(to)
	return ok1 != ok2 || ok1 && *s1 != *s2
}

// IndexPartAttrChanged reports if the index-part attributes were changed.
func (*diff) IndexPartAttrChanged(from, to *sqlschema.IndexPart) bool {
	p1 := &IndexColumnProperty{NullsFirst: from.Descending, NullsLast: !from.Descending}
	sqlschema.Has(from.Attrs, p1)
	p2 := &IndexColumnProperty{NullsFirst: to.Descending, NullsLast: !to.Descending}
	sqlschema.Has(to.Attrs, p2)
	return p1.NullsFirst != p2.NullsFirst || p1.NullsLast != p2.NullsLast
}

// ReferenceChanged reports if the foreign key referential action was changed.
func (*diff) ReferenceChanged(from, to sqlschema.ReferenceOption) bool {
	// According to PostgreSQL, the NO ACTION rule is set
	// if no referential action was defined in foreign key.
	if from == "" {
		from = sqlschema.NoAction
	}
	if to == "" {
		to = sqlschema.NoAction
	}
	return from != to
}

func (d *diff) typeChanged(from, to *sqlschema.Column) (bool, error) {
	fromT, toT := from.Type.Type, to.Type.Type
	if fromT == nil || toT == nil {
		return false, fmt.Errorf("postgres: missing type information for column %q", from.Name)
	}
	if reflect.TypeOf(fromT) != reflect.TypeOf(toT) {
		return true, nil
	}
	var changed bool
	switch fromT := fromT.(type) {
	case *sqlschema.BinaryType, *BitType, *sqlschema.BoolType, *sqlschema.DecimalType, *sqlschema.FloatType,
		*IntervalType, *sqlschema.IntegerType, *sqlschema.JSONType, *SerialType, *sqlschema.SpatialType,
		*sqlschema.StringType, *sqlschema.TimeType, *NetworkType, *UserDefinedType:
		t1, err := FormatType(toT)
		if err != nil {
			return false, err
		}
		t2, err := FormatType(fromT)
		if err != nil {
			return false, err
		}
		changed = t1 != t2
	case *sqlschema.EnumType:
		toT := toT.(*sqlschema.EnumType)
		// Column type was changed if the underlying enum type was changed or values are not equal.
		changed = !sqlutil.ValuesEqual(fromT.Values, toT.Values) || fromT.T != toT.T ||
			(toT.Schema != nil && fromT.Schema != nil && fromT.Schema.Name != toT.Schema.Name)
	case *CurrencyType:
		toT := toT.(*CurrencyType)
		changed = fromT.T != toT.T
	case *UUIDType:
		toT := toT.(*UUIDType)
		changed = fromT.T != toT.T
	case *XMLType:
		toT := toT.(*XMLType)
		changed = fromT.T != toT.T
	case *ArrayType:
		toT := toT.(*ArrayType)
		// Same type.
		if changed = fromT.T != toT.T; !changed {
			// In case it is an enum type, compare its values.
			fromE, ok1 := fromT.Type.(*sqlschema.EnumType)
			toE, ok2 := toT.Type.(*sqlschema.EnumType)
			changed = ok1 && ok2 && !sqlutil.ValuesEqual(fromE.Values, toE.Values)
			break
		}
		// In case the desired schema is not normalized, the string type can look different even
		// if the two strings represent the same array type (varchar(1), character varying (1)).
		// Therefore, we try by comparing the underlying types if they were defined.
		if fromT.Type != nil && toT.Type != nil {
			t1, err := FormatType(fromT.Type)
			if err != nil {
				return false, err
			}
			t2, err := FormatType(toT.Type)
			if err != nil {
				return false, err
			}
			// Same underlying type.
			changed = t1 != t2
		}
	default:
		return false, &sqlschema.UnsupportedTypeError{Type: fromT}
	}
	return changed, nil
}

// Default IDENTITY attributes.
const (
	defaultIdentityGen  = "BY DEFAULT"
	defaultSeqStart     = 1
	defaultSeqIncrement = 1
)

// identityChanged reports if one of the identity attributes was changed.
func identityChanged(from, to []sqlschema.Attr) bool {
	i1, ok1 := identity(from)
	i2, ok2 := identity(to)
	if !ok1 && !ok2 || ok1 != ok2 {
		return ok1 != ok2
	}
	return i1.Generation != i2.Generation || i1.Sequence.Start != i2.Sequence.Start || i1.Sequence.Increment != i2.Sequence.Increment
}

func identity(attrs []sqlschema.Attr) (*Identity, bool) {
	i := &Identity{}
	if !sqlschema.Has(attrs, i) {
		return nil, false
	}
	if i.Generation == "" {
		i.Generation = defaultIdentityGen
	}
	if i.Sequence == nil {
		i.Sequence = &Sequence{Start: defaultSeqStart, Increment: defaultSeqIncrement}
		return i, true
	}
	if i.Sequence.Start == 0 {
		i.Sequence.Start = defaultSeqStart
	}
	if i.Sequence.Increment == 0 {
		i.Sequence.Increment = defaultSeqIncrement
	}
	return i, true
}

// formatPartition returns the string representation of the
// partition key according to the PostgreSQL format/grammar.
func formatPartition(p Partition) (string, error) {
	b := &sqlutil.Builder{QuoteChar: '"'}
	b.P("PARTITION BY")
	switch t := strings.ToUpper(p.T); t {
	case PartitionTypeRange, PartitionTypeList, PartitionTypeHash:
		b.P(t)
	default:
		return "", fmt.Errorf("unknown partition type: %q", t)
	}
	if len(p.Parts) == 0 {
		return "", errors.New("missing parts for partition key")
	}
	b.Wrap(func(b *sqlutil.Builder) {
		b.MapComma(p.Parts, func(i int, b *sqlutil.Builder) {
			switch k := p.Parts[i]; {
			case k.Column != "":
				b.Ident(k.Column)
			case k.Expr != nil:
				b.P(sqlutil.MayWrap(k.Expr.(*sqlschema.RawExpr).X))
			}
		})
	})
	return b.String(), nil
}

// indexStorageParams returns the index storage parameters from the attributes
// in case it is there, and it is not the default.
func indexStorageParams(attrs []sqlschema.Attr) (*IndexStorageParams, bool) {
	s := &IndexStorageParams{}
	if !sqlschema.Has(attrs, s) {
		return nil, false
	}
	if !s.AutoSummarize && (s.PagesPerRange == 0 || s.PagesPerRange == defaultPagePerRange) {
		return nil, false
	}
	return s, true
}

// indexIncludeChanged reports if the INCLUDE attribute clause was changed.
func indexIncludeChanged(from, to []sqlschema.Attr) bool {
	var fromI, toI IndexInclude
	if sqlschema.Has(from, &fromI) != sqlschema.Has(to, &toI) || len(fromI.Columns) != len(toI.Columns) {
		return true
	}
	for i := range fromI.Columns {
		if fromI.Columns[i] != toI.Columns[i] {
			return true
		}
	}
	return false
}

func trimCast(s string) string {
	i := strings.LastIndex(s, "::")
	if i == -1 {
		return s
	}
	for _, r := range s[i+2:] {
		if r != ' ' && !unicode.IsLetter(r) {
			return s
		}
	}
	return s[:i]
}
