// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: databases.sql

package repository

import (
	"context"
)

const createDatabase = `-- name: CreateDatabase :exec
INSERT INTO
    databases (db_name, db_owner)
VALUES
    ($1, (SELECT id FROM accounts WHERE account_address = $2))
`

type CreateDatabaseParams struct {
	DbName         string
	AccountAddress string
}

func (q *Queries) CreateDatabase(ctx context.Context, arg *CreateDatabaseParams) error {
	_, err := q.exec(ctx, q.createDatabaseStmt, createDatabase, arg.DbName, arg.AccountAddress)
	return err
}

const dropDatabase = `-- name: DropDatabase :exec
DELETE FROM
    databases
WHERE
    db_name = $1
    AND db_owner = (SELECT id FROM accounts WHERE account_address = $2)
`

type DropDatabaseParams struct {
	DbName         string
	AccountAddress string
}

func (q *Queries) DropDatabase(ctx context.Context, arg *DropDatabaseParams) error {
	_, err := q.exec(ctx, q.dropDatabaseStmt, dropDatabase, arg.DbName, arg.AccountAddress)
	return err
}
