// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: spend.sql

package repository

import (
	"context"
)

const spend = `-- name: Spend :exec
WITH previous_nonce AS (
   SELECT
      nonce
   FROM
      accounts
   WHERE
      account_address = $1
   FOR UPDATE
)
UPDATE
   accounts a
SET
   balance = a.balance - $2,
   spent = a.spent + $2,
   nonce = $3
WHERE
   a.account_address = $1
   AND a.balance >= $2
`

type SpendParams struct {
	AccountAddress string
	Balance        string
	Nonce          int64
}

func (q *Queries) Spend(ctx context.Context, arg *SpendParams) error {
	_, err := q.exec(ctx, q.spendStmt, spend, arg.AccountAddress, arg.Balance, arg.Nonce)
	return err
}
