version: '3'

tasks:
  update:
    desc: Updates protobuf git submodules
    cmds:
      - git submodule update --remote

  compile:v0:
    desc: Compiles v0 protobuf
    internal: true
    deps: [update]
    # TODO: enforce after github action supprort new versionning scheme
    #    version above 3.21 is not supported by github actions,
    #    preconditions:
    #      - sh: a="libprotoc 3.21.12";b=`protoc --version`;test "$a" = "$b"
    #        msg: "Protobuf compiler version is not 3.21.12, please install the correct version"
    cmds:
      - |
        protoc -I ./proto \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v0/api \
        proto/kwil/*/v0/*.proto
    sources:
      - proto/kwil/*/v0/*.proto
    generates:
      - api/protobuf/*/v0/*.go
      - api/openapi-spec/api/v0/api.swagger.json

  compile:v1:
    desc: Compiles v1 protobuf
    cmds:
      - |
        protoc -I ./proto \
        --go_out=. --go_opt module=github.com/kwilteam/kwil-db \
        --go-grpc_out=. --go-grpc_opt module=github.com/kwilteam/kwil-db \
        --grpc-gateway_out=. --grpc-gateway_opt module=github.com/kwilteam/kwil-db --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v1/api \
        proto/kwil/*/v1/*.proto
    sources:
      - proto/kwil/*/v1/*.proto
    generates:
      - api/protobuf/*/v1/*.go
      - api/openapi-spec/api/v1/api.swagger.json

  gogo-gen:
    desc: Compiles protobuf with gogo
    cmds:
      # - echo "dsds"
      - docker run --rm -v /Users/charithabandi/Desktop/kwil/dev/join-consensus:/workspace --workdir /workspace ghcr.io/cosmos/proto-builder:0.13.0 find ./proto/kwil/node/ -name "*.proto" -exec clang-format -i {} \;
      - docker run --rm -v /Users/charithabandi/Desktop/kwil/dev/join-consensus:/workspace --workdir /workspace ghcr.io/cosmos/proto-builder:0.13.0 buf lint --path ./proto/kwil/node/ --error-format=json
      - echo "Generating Protobuf files"
      - docker run --rm -v /Users/charithabandi/Desktop/kwil/dev/join-consensus:/workspace --workdir /workspace ghcr.io/cosmos/proto-builder:0.13.0 sh ./scripts/gogoprotogen.sh
    sources:
      - proto/kwil/node/v1/*.proto
    generates:
      - api/protobuf/kwil/node/v1/*.go
    # vars:
    #   - protoImage: 'docker run --rm -v .:workspace --workdir /workspace ghcr.io/cosmos/proto-builder:0.13.0'
