version: '3'

tasks:
  compile:all:
    desc: Compiles all protobufs
    cmds:
      - |
        protoc -I ./proto \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v0/api \
        proto/kwil/common/v0/*.proto \
        proto/kwil/account/v0/*.proto \
        proto/kwil/pricing/v0/*.proto \
        proto/kwil/config/v0/*.proto \
        proto/kwil/tx/v0/*.proto
    sources:
      - proto/kwil/common/v0/*.proto \
      - proto/kwil/account/v0/*.proto \
      - proto/kwil/pricing/v0/*.proto \
      - proto/kwil/config/v0/*.proto \
      - proto/kwil/tx/v0/*.proto
    generates:
      - protobuf/account/v0
      - protobuf/common/v0
      - protobuf/pricing/v0
      - protobuf/config/v0
      - protobuf/tx/v0

  compile:account:
    desc: Compiles the protobuf for the Account Service
    deps:
      - compile:common
    cmds:
      - |
        protoc -I api/protobuf \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v0/api \
        api/protobuf/kwil/account/v0/*.proto
    sources:
      - api/protobuf/kwil/account/v0/*.proto
    generates:
      - api/protobuf/kwil/account/v0/gen/go/*
      - api/openapi-spec/api/v0/*

  compile:pricing:
    desc: Compiles the protobuf for the Pricing Service
    deps:
      - compile:common
    cmds:
      - |
        protoc -I api/protobuf \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v0/api \
        api/protobuf/kwil/pricing/v0/*.proto
    sources:
      - api/protobuf/kwil/pricing/v0/*.proto
    generates:
      - api/protobuf/kwil/pricing/v0/gen/go/*
      - api/openapi-spec/api/v0/*

  compile:config:
    desc: Compiles the protobuf for Config service
    deps:
      - compile:common
    cmds:
      - |
        protoc -I api/protobuf \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v0/api \
        api/protobuf/kwil/config/v0/*.proto
    sources:
      - api/protobuf/kwil/config/v0/*.proto
    generates:
      - api/protobuf/kwil/config/v0/gen/go/*
      - api/openapi-spec/api/v0/*


  compile:tx:
    desc: Compiles the protobuf for Tx service
    deps:
      - compile:common
    cmds:
      - |
        protoc -I api/protobuf \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v0/api \
        api/protobuf/kwil/tx/v0/*.proto
    sources:
      - api/protobuf/kwil/tx/v0/*.proto
    generates:
      - api/protobuf/kwil/tx/v0/gen/go/*
      - api/openapi-spec/api/v0/*

  compile:common:
    desc: Compiles common protobufs
    cmds:
      - |
        protoc -I api/protobuf \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        api/protobuf/kwil/common/v0/*.proto
    sources:
      - api/protobuf/kwil/common/v0/*.proto
    generates:
      - api/protobuf/kwil/common/v0/gen/go/*