version: '3'

tasks:
  compile:v0:
    desc: Compiles v0 protobuf
    internal: true
    deps: [update]
    preconditions:
      - sh: a="libprotoc 23.4";b=`protoc --version`;test "$a" = "$b"
        msg: "Protobuf compiler version is not 23.4, please install the correct version"
    cmds:
      - |
        protoc -I ./proto \
        --go_out=. --go_opt module=kwil \
        --go-grpc_out=. --go-grpc_opt module=kwil \
        --grpc-gateway_out=. --grpc-gateway_opt module=kwil --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v0/api \
        proto/kwil/*/v0/*.proto
    sources:
      - proto/kwil/*/v0/*.proto
    generates:
      - api/protobuf/*/v0/*.go
      - api/openapi-spec/api/v0/api.swagger.json

  compile:v1:
    desc: Compiles v1 protobuf
    preconditions:
      - sh: a="libprotoc 23.4";b=`protoc --version`;test "$a" = "$b"
        msg: "Protobuf compiler version is not 23.4, please install the correct version"
    cmds:
      - |
        protoc -I ./proto \
        --go_out=. --go_opt module=github.com/kwilteam/kwil-db \
        --go-grpc_out=. --go-grpc_opt module=github.com/kwilteam/kwil-db \
        --grpc-gateway_out=. --grpc-gateway_opt module=github.com/kwilteam/kwil-db --grpc-gateway_opt generate_unbound_methods=true \
        --openapiv2_out=. --openapiv2_opt allow_merge=true --openapiv2_opt merge_file_name=api/openapi-spec/api/v1/api \
        proto/kwil/*/v1/*.proto
    sources:
      - proto/kwil/*/v1/*.proto
    generates:
      - api/protobuf/*/v1/*.go
      - api/openapi-spec/api/v1/api.swagger.json
