# manual-test-kgw.yaml run kgw-test with manual inputs: kwil-db-branch and kgw-branch.
name: manual-test-kgw

on:
  workflow_dispatch:
    inputs:
      kdb-sha:
        description: 'kwil-db sha to be tested. If provided, it will used instead of branch'
        required: false
        type: string
      kdb-branch:
        description: 'kwil-db branch to be tested'
        required: false
        type: string
      kgw-branch:
        description: 'kgw branch to be tested'
        required: true
        type: string

jobs:
  kgw-test-manual:
    name: Run manual KGW test
    uses: ./.github/workflows/kgw-test-reuse.yaml
    with:
      kdb-sha: ${{ github.event.inputs.kdb-sha }}
      kdb-branch: ${{ github.event.inputs.kdb-branch }}
      kgw-branch: ${{ github.event.inputs.kgw-branch }}
    secrets:
      kgw-access-token: ${{ secrets.KGW_MACH_SECRET_FOR_KWILDB }}